### ISSUE TITLE
I have a problem Obfuscating Smali code...  

### ISSUE THREAD

**Issue by stesep** [oddcod3/Phantom-Evasion#63] opened 2020-02-03 01:10 UTC
[>] Obfuscating Smali code...                                               
                                                                            
Traceback (most recent call last):
  File "phantom-evasion.py", line 402, in <module>
    CompleteMenu()
  File "phantom-evasion.py", line 190, in CompleteMenu
    Phantom_lib.ModuleLauncher(module_type)
  File "Setup/Phantom_lib.py", line 937, in ModuleLauncher
    LoadExecModule(M_type,ModOpt)
  File "Setup/Phantom_lib.py", line 591, in LoadExecModule
    ApkSmaliObfuscator_android(ModOpt)
  File "Modules/payloads/MsfvenomObfuscateBackdoor_android.py", line 287, in ApkSmaliObfuscator_android
    os.rename("msf_smali/smali/com/metasploit","msf_smali/smali/com/" + ModOpt["Metaspl"])
FileNotFoundError: [Errno 2] No such file or directory: 'msf_smali/smali/com/metasploit' -> 'msf_smali/smali/com/rsozzppe'

**Comment by ghost** [comment] 2020-02-10 07:35
I have the same problem. Looks to me as if someone modified the script. It worked on the first run. I go to run it again and get the same error as you. The script renamed to folders in the smali dir.

**Comment by oddcod3** [comment] 2020-02-13 08:38
Duplicate of #65

**Closed as completed by oddcod3** 2020-02-13 08:38 UTC
