### ISSUE TITLE
not sure

### ISSUE THREAD

**Issue by SphiwokuhleS** [oddcod3/Phantom-Evasion#23] opened 2018-07-16 18:05 UTC
Unable to open 'resigned.apk' as zip archive
Traceback (most recent call last):
  File "phantom-evasion.py", line 422, in <module>
    complete_menu()
  File "phantom-evasion.py", line 276, in complete_menu
    Phantom_lib.droidmare_launcher()
  File "Setup/Phantom_lib.py", line 1552, in droidmare_launcher
    os.remove("msf_rebuild.apk")
OSError: [Errno 2] No such file or directory: 'msf_rebuild.apk'

**Comment by oddcod3** [comment] 2018-07-19 12:13
Duplicate of  #20

**Closed** 2018-12-16 00:45 UTC
