### ISSUE TITLE
smali code

### ISSUE THREAD

**Issue by ghost** [oddcod3/Phantom-Evasion#64] opened 2020-02-10 10:25 UTC
Traceback (most recent call last):
  File "./phantom-evasion.py", line 402, in <module>
    CompleteMenu()
  File "./phantom-evasion.py", line 190, in CompleteMenu
    Phantom_lib.ModuleLauncher(module_type)
  File "Setup/Phantom_lib.py", line 937, in ModuleLauncher
    LoadExecModule(M_type,ModOpt)
  File "Setup/Phantom_lib.py", line 591, in LoadExecModule
    ApkSmaliObfuscator_android(ModOpt)
  File "Modules/payloads/MsfvenomObfuscateBackdoor_android.py", line 287, in ApkSmaliObfuscator_android
    os.rename("msf_smali/smali/com/metasploit","msf_smali/smali/com/" + ModOpt["Metaspl"])
OSError: [Errno 2] No such file or directory

**Comment by oddcod3** [comment] 2020-02-13 08:38
Duplicate of #65

**Closed as completed by oddcod3** 2020-02-13 08:38 UTC
